# Generated by Django 3.2.19 on 2023-12-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseNo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=255)),
                ('courseGrade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuNo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stuName', models.CharField(max_length=255)),
                ('stuAge', models.CharField(max_length=255)),
                ('stuSex', models.CharField(max_length=255)),
                ('stuGrade', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuScore', models.CharField(max_length=255)),
                ('courseGrade', models.CharField(max_length=255)),
                ('courseNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StuManageApp.course')),
                ('stuNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StuManageApp.student')),
            ],
        ),
    ]
